### ISSUE TITLE
Bug - Toons coming out of the water vanish until another animation plays.

### ISSUE THREAD

**Issue by ThePlayerZero** [PLAYERZER0STUDIOS/Open-Fantasy#37]
Toons coming out of the water vanish until an animation is played like going into a Tunnel or building

![toontown-screenshot-Thu-Jul-21-14-59-31-2022-79426](https://user-images.githubusercontent.com/68795576/180295386-7083373b-73da-446b-bfe0-81e54a5f9b4d.jpg)

![toontown-screenshot-Thu-Jul-21-14-59-34-2022-80010](https://user-images.githubusercontent.com/68795576/180295409-b2479dc4-d659-49a2-80be-417e941f5f71.jpg)

![toontown-screenshot-Thu-Jul-21-15-00-30-2022-92173](https://user-images.githubusercontent.com/68795576/180295429-81971f8d-2f48-4591-871c-9ee4097a71d0.jpg)

![toontown-screenshot-Thu-Jul-21-15-00-32-2022-92599](https://user-images.githubusercontent.com/68795576/180295438-99e3e9c1-f911-4ea3-9a73-3bb601b77604.jpg)

[toontown-220721_145242.log](https://github.com/PLAYERZER0STUDIOS/Open-Fantasy/files/9162012/toontown-220721_145242.log)

**Comment by ThePlayerZero** [comment]
Just a note, this first started happening when the Orbital Camera was added.

**Comment by DarthNihilus1** [comment]
Interesting ik i had this issue with toontown galaxy. Interesting to know its orbital that causes it

**Comment by ThePlayerZero** [comment]
> Interesting ik i had this issue with toontown galaxy. Interesting to know its orbital that causes it

Wild. If you find a fix for it, please be sure to implement it to Open-Fantasy whenever you can!

**Comment by ThePlayerZero** [comment]
This has been patched. All of it's in the OrbitalCamera.py file!
